version: '3.9'

# networks:
#   gitlab-net:
#     name: gitlab-net
#     driver: bridge

# volumes:
#   redis-data:
#   postgresql-data:
#   gitlab-data:

services:
  # redis:
  #     restart: always
  #     image: redis:latest
  #     volumes:
  #     - redis-data:/data
  # postgresql:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #   - postgresql-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=gitlab_ce
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    # depends_on:
    #   - redis
    #   - postgresql
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:80'
      - '2224:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    # networks:
    #   - gitlab-net
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab-web
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/srv/gitlab/gitlab-runner:/etc/gitlab-runner'
    # networks:
    #   - gitlab-net